[project]
name = "selfplay"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flax>=0.10",
    "imageio>=2.37.3",
    "imageio-ffmpeg>=0.6.0",
    "jax>=0.4.35",
    "matplotlib>=3.11.1",
    "mujoco>=3.2.5",
    "mujoco-mjx>=3.2.5",
    "numpy>=2.5.1",
    "optax>=0.2",
]

[project.optional-dependencies]
cuda = ["jax[cuda12]>=0.4.35"]
